comit-network/create-comit-app

- src/new.rs
- src/start_env.rs
Clean-up if there is a failure when handling keys, envfile or dockers.
> Cleanup at failure

- src/create_comit_app.rs
- src/main.rs
- src/new.rs
Git folders are also deleted to allow user to create new git repo
out of project.
> `new` command: User must pass project name

- src/docker/cnd.rs
> Correct var name

- src/docker/blockchain/bitcoin.rs
- src/docker/blockchain/ethereum.rs
- src/docker/btsieve.rs
- src/docker/cnd.rs
- src/docker/mod.rs
- src/start_env.rs
> Be sure to write cnd urls for both instances

- src/docker/blockchain/bitcoin.rs
- src/docker/mod.rs
- src/new.rs
- src/start_env.rs
Remove TODOs that are done, tracked or somehow invalid. I encourage someone else to have a look at the other 4 remaining TODOs and do the same for those (just commit to this PR if you want).
> Remove most TODOs

- src/new.rs
Instead there will be a bunch of untracked files present.
Fixes #31.
> Do not do an initial commit

- CHANGELOG.md
> Update changelog for #49, #57, #58 & #59

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/docker/blockchain/ethereum.rs
- src/start_env/mod.rs
- src/start_env/temp_fs.rs
Follow-up of comments done on #57.
> #57 Follow-up

- .npm/package.json
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Publish create-comit-app on npmjs.com.
- Fix the odd initial Ether amount.
> Release 0.2.1

- README.md
> Include instructions to run create-comit-app from npm package

- src/new.rs
> Improve feedback message for new command success

- Cargo.lock
- Cargo.toml
- src/docker/blockchain/bitcoin.rs
- src/start_env/mod.rs
> Remove bitcoincore rpc client

- src/start_env/mod.rs
Quick fix for now. Proper fix here: #94.
> Correctly serialize the erc20 contract address to the env file

- .npm/package.json
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Given the big feature we added, this is worth a minor release!
> Release version 0.3.0

- .github/workflows/release-bin.yml
> Build and upload linux release binary

- .github/workflows/release-bin.yml
- Cargo.lock
- Cargo.toml
> Release Mac OS Binary

- Cargo.lock
- Cargo.toml
> Need unix-socket feature to access docker

- new_project/examples/btc-eth/yarn.lock
- new_project/examples/erc20-btc/package.json
- new_project/examples/erc20-btc/yarn.lock
- yarn.lock files were not in sync with respective package.json files.
- Typo present in erc20 package.json file.
> Update yarn.lock files

- src/docker/mod.rs
- src/print_progress.rs
- src/start_env/clean_up.rs
- src/start_env/mod.rs
- src/start_env/start.rs
Resolves #84.
Output:
```
Creating Docker network (create-comit-app)...✓
Starting Ethereum node...✓
Starting Bitcoin node...✓
Panic received, cleaning up...✓
panicked at 'Random panic!', src/start_env/start.rs:135:5
Process finished with exit code 101
```
> Clean-up on panic

- CHANGELOG.md
> Update changelog for #121

- new_project/examples/erc20_btc/package.json
- new_project/examples/erc20_btc/src/index.ts
- new_project/examples/erc20_btc/yarn.lock
How it looks like now:
```
▶ yarn run start
yarn run v1.19.1
warning ../../package.json: No license field
$ DOTENV_CONFIG_PATH=$HOME/.create-comit-app/env ts-node -r dotenv/config ./src/index.ts
Maker Ethereum address:  0x1925c0a2E0Cd8B4C327f30733A9110CE5956048C
Taker Ethereum address:  0x2c9b72bFEB96FFb4bb3F53841004dFad64B91eF2
Maker Bitcoin balance: 10. Erc20 Token balance: 100
Taker Bitcoin balance: 10. Erc20 Token balance: 100
Swap started! Swapping 10 tokens @ contract address 0x62d69f6867a0a084c6d313943dc22023bc263691 for 1 bitcoin
Continue?
ERC20 contract deployed! TXID:  0x7fbf1cd5408e60154ddbc52a5d962b3b5124593cdc9ee369f1239692e7b77c90
Continue?
ERC20 contract funded! TXID:  0x4ca22be6ea03b508b570e5efcaa5be7c9ca2900fc0b8abc4d7673ed617457de5
Continue?
Bitcoin contract funded! …
```
> Log ERC20 balance

- new_project/examples/erc20_btc/package.json
- new_project/examples/erc20_btc/src/index.ts
- new_project/examples/erc20_btc/tsconfig.json
- new_project/examples/erc20_btc/tslint.json
- new_project/examples/erc20_btc/yarn.lock
- Ensure valid comit-sdk release is use
- Enable tslint
- Automatically exit once finished
> Some cleanup

- .dependabot/config.yml
- .mergify.yml
- bors.toml
> Setup bors, dependabot and mergify

- CHANGELOG.md
- new_project/examples/erc20_btc/src/index.ts
ERC20 in log was wrong. 
Made messages similar.
> correct log output

- Cargo.lock
- src/env/start.rs
Not sure if everybody will like this - it is a bit more "object" drive, but I find it way clearer to understand. 
I don't especially like the name `BitcoinAccount`, if you have something better happy for suggestions)
> make bitcoin and ethereum key generation more readable

- Cargo.lock
- Cargo.toml
- src/docker/blockchain/bitcoin.rs
- src/docker/mod.rs
- src/env/clean_up.rs
- src/env/mod.rs
- src/env/start.rs
- src/env/temp_fs.rs
I wanted to use anyhow in another place, so here is some ground-work that moves most of the codebase to anyhow.
> Refactor most error handling to use anyhow

- .npm/package.json
- CHANGELOG.md
- Cargo.toml
- Correct log messages in ERC20-BTC example.
- Added a simple negotiation protocol prototype to the example in `seperate_apps`.
- Setting the project name in the `package.json` when running the `new` command.
- Clean up the environment if a panic occurs.
- `force-clean-env` command to stop all services.
- `separate_apps` example where the taker and maker must be started from different terminal to give a better peer-to-peer feeling.
> Release 0.4.0

- src/env/start.rs
This is a follow-up PR for #187. 
Initially I wanted to avoid storing any kind of derived data in the struct. However, we can't do that because deriving can fail and we cannot (yet) properly handle those errors at the place where we would derive them.
> Move logic for creating new accounts onto structs

- src/cnd_settings.rs
> Simplify Cors setting representation

- CHANGELOG.md
- new_project/examples/separate_apps/package.json
- new_project/examples/separate_apps/src/maker.ts
- new_project/examples/separate_apps/yarn.lock
Upgrade to comit-sdk 0.7.1 to:
- Fix auto-accept issue
- Use swap search by id in negotiation protocol
> Fix auto-accept

- CHANGELOG.md
- README.md
- new_project/examples/separate_apps/README.md
- new_project/examples/separate_apps/src/lib.ts
- new_project/examples/separate_apps/src/maker.ts
- new_project/examples/separate_apps/src/taker.ts
cleaned up PR, there should not be additional changes @D4nte
> add comments to the separate apps example

- .github/workflows/CI.yml
- .github/workflows/release-bin.yml
- .npm/package.json
> Add npm check and release

- new_project/examples/btc_eth/package.json
- new_project/examples/btc_eth/src/index.ts
- new_project/examples/btc_eth/yarn.lock
- new_project/examples/erc20_btc/package.json
- new_project/examples/erc20_btc/src/index.ts
- new_project/examples/erc20_btc/yarn.lock
- new_project/examples/separate_apps/package.json
- new_project/examples/separate_apps/src/lib.ts
- new_project/examples/separate_apps/src/maker.ts
- new_project/examples/separate_apps/src/taker.ts
- new_project/examples/separate_apps/yarn.lock
> Use createActor function from comit-sdk

- new_project/.gitignore
- new_project/README.md
- new_project/examples/btc_eth/src/index.ts
- new_project/examples/erc20_btc/src/index.ts
- new_project/examples/separate_apps/src/lib.ts
- new_project/package.json
- new_project/src/index.js
> Improve template project experience

- .npm/package.json
- README.md
- new_project/README.md
- new_project/examples/README.md
- new_project/examples/btc_eth/README.md
- new_project/examples/btc_eth/package.json
- new_project/examples/btc_eth/src/index.ts
- new_project/examples/btc_eth/yarn.lock
- new_project/examples/erc20_btc/README.md
- new_project/examples/erc20_btc/package.json
- new_project/examples/erc20_btc/src/index.ts
- new_project/examples/erc20_btc/yarn.lock
- new_project/examples/separate_apps/README.md
- new_project/examples/separate_apps/package.json
- new_project/examples/separate_apps/src/lib.ts
- new_project/examples/separate_apps/yarn.lock
- new_project/package.json
- new_project/src/index.js
- tests/run_example.sh
Note: please review with care given what the original issue described. I went a bit fast.
Fixes #114.
Except for needing to download `create-comit-app` more than once. An issue will be created to track the optimisation that would fix it.
> No need to know about CCA.

- new_project/examples/btc_eth/src/index.ts
- new_project/examples/separate_apps/src/maker.ts
- new_project/examples/separate_apps/src/taker.ts
- src/docker/ethereum.rs
Swap semi-believable rates for Ether <-> Bitcoin.  50 Ether is approx 1 bitcoin.  In order to do this we need to fund more Ether, fund 1000.
> Use believable rates

- .github/workflows/CI.yml
- .github/workflows/release-bin.yml
- .npm/download.js
- .npm/makeArchiveName.js
- .npm/printArchiveName.js
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Makefile
- README.md
- new_project/examples/btc_eth/package.json
- new_project/examples/btc_eth/src/index.ts
- new_project/examples/erc20_btc/package.json
- new_project/examples/erc20_btc/src/index.ts
- new_project/examples/separate_apps/package.json
- new_project/examples/separate_apps/src/lib.ts
- new_project/package.json
- new_project/src/index.js
- src/docker/bitcoin.rs
- src/docker/cnd.rs
- src/docker/ethereum.rs
- src/docker/mod.rs
- src/env/clean_up.rs
- src/env/mod.rs
- src/env/start.rs
> Make it work on windows :tada:

- CHANGELOG.md
- new_project/examples/btc_eth/package.json
- new_project/examples/btc_eth/yarn.lock
- new_project/examples/erc20_btc/package.json
- new_project/examples/erc20_btc/yarn.lock
- new_project/examples/separate_apps/package.json
- new_project/examples/separate_apps/src/lib.ts
- new_project/examples/separate_apps/yarn.lock
- new_project/package.json
This brings in the Ether float fix needed for testnet.
> Upgrade to comit-sdk@0.8.0

- .github/workflows/CI.yml
- Makefile
Ensure lock files are kept up to date.
Tested: https://github.com/comit-network/create-comit-app/pull/277/checks?check_run_id=339354550
> Check Lock files

- build.rs
To achieve this, we need to emit the proper path to cargo.
Fixes #306.
> Avoid rebuilding the binary if not necessary

- CHANGELOG.md
- build.rs
- src/new.rs
Implement comments I made on #305
> Follow-up 305

- Makefile
- create/new_project/examples/btc_eth/package.json
- create/new_project/examples/btc_eth/yarn.lock
- create/new_project/examples/erc20_btc/package.json
- create/new_project/examples/erc20_btc/yarn.lock
- create/new_project/examples/separate_apps/package.json
- create/new_project/examples/separate_apps/yarn.lock
- create/new_project/package.json
- tests/run_example.sh
> Upgrade comit-scripts to 0.8.0

- create/CHANGELOG.md
- create/npm/download.js
Fix 404 error when doing `yarn create comit-app`
> Fix 404 error

- .github/workflows/auto-assign.yml
I do more PR on this repo so better test it here.
> Auto assign PRs to author

- scripts/CHANGELOG.md
- scripts/npm/download.js
Same issue than with create-comit-app...
> Fix start-env

- scripts/CHANGELOG.md
- scripts/npm/download.js
Old binary name was used making it not possible to install comit-scripts
> Fix name of binary

- .dependabot/config.yml
> Remove duplicate dependabot configuration entry

- scripts/src/env/start.rs
> remove bitcoin node rpc url

- create/src/new.rs
- scripts/src/env/mod.rs
comit-scripts now handles start-env.
one cannot run it with create-comit-app.
> update create message

- README.md
- logo.svg
How it would look: https://github.com/comit-network/create-comit-app/blob/update-readme/README.md
Notes:
* asciinema video for "quick start" in "Getting Started".
* Detailed Guidelines on Installation and running demos and examples
* Extending the Appendix a bit to add info that this is actually a rust project...
> Enhance README and add specific logo

- create/CHANGELOG.md
- create/new_project/examples/btc_eth/package.json
- create/new_project/examples/btc_eth/src/maker.ts
- create/new_project/examples/btc_eth/src/taker.ts
- create/new_project/examples/btc_eth/yarn.lock
Incorporates SDK changes from comit-network/comit-js-sdk#116
Related to comit-network/comit-js-sdk#89
> Use new `TakerNegotiator` interface

- .github/workflows/trigger-sync-labels.yml
Already tested on comit-js-sdk.
For coblox/admin#85
> Add trigger to sync labels

- create/new_project/examples/btc_eth/src/lib.ts
- create/new_project/examples/btc_eth/src/maker.ts
Fixed some formatting which were failing on this PR: https://github.com/comit-network/create-comit-app/pull/517
> Fix some formatting errors

- create/new_project/examples/btc_eth/src/maker.ts
minor renaming for better understandability.
> Clearer variable name for swap for maker

- Cargo.lock
- scripts/Cargo.toml
- scripts/src/config.rs
- scripts/src/docker/bitcoin.rs
- scripts/src/docker/ethereum.rs
- scripts/src/env/start.rs
- scripts/src/lib.rs
Fund additional Bitcoin and Ethereum addresses specified in an optional config file.
>  Fund addresses specified in a config file

- .github/workflows/CI.yml
- scripts/src/docker/bitcoin.rs
- scripts/src/docker/ethereum.rs
Have not tested this yet locally
> Map default blockchain ports to host
