comit-network/create-comit-app

- Cargo.lock
- Cargo.toml
- src/new.rs
`create-comit-app new <project-name>` now creates a git repository with a clean history. The initial commit adds all the hello-swap files.
It also fixes a bug that was causing the command to fail because it couldn't `git clone`:
```
```'Failed to clone hello-swap: Error { code: -1, klass: 16, message: "there is no TLS stream available" }', src/new.rs:8:22```
```
Luckily, there was no need to introduce an unwanted libssl dependency to fix it.
> Create git repository with initial commit

- README.md
`create-comit-app start-env` has to be run inside the hello-swap project folder.
> Add missing step in README.md

- src/start_env.rs
Since they are not cleaned up at the end a user can at least easily locate and remove it if they want to.
> Keep temporary directory in known location

- README.md
Several participants in the workshop just blindly followed the instructions in order. 
Consequently they did `simple setup` and `hard` setup...
In order to avoid this I'd suggest we move the `hard setup` section to an appendix. Or we just remove it completely. This is a PR to move it to an appendix. 
Feel free to adapt this. I'm not sure what the best solution is yet.
> Simplify readme by moving hard-setup to appendix

- src/docker/mod.rs
- src/lib.rs
- src/print_progress.rs
- src/start_env/mod.rs
Resolves #54.
First time doing `start-env`:
```
Creating Docker network (create-comit-app)...✓
Starting Bitcoin node...Downloading coblox/bitcoin-core:0.17.0...✓
Starting Ethereum node...Downloading parity/parity:v2.5.0...✓
Writing configuration in env file...✓
Starting two cnds...Downloading comitnetwork/cnd:0.3.0...✓
🎉 Environment is ready, time to create a COMIT app!
```
The other times:
```
Creating Docker network (create-comit-app)...✓
Starting Bitcoin node...✓
Starting Ethereum node...✓
Writing configuration in env file...✓
Starting two cnds...✓
🎉 Environment is ready, time to create a COMIT app!
```
> Lazily pull docker images

- CHANGELOG.md
- src/start_env/mod.rs
```
[maker] Bitcoin balance: 10. Ether balance: 9
[taker] Bitcoin balance: 10. Ether balance: 9
```
I used a hex string because 9 Ether is bigger than `u64` and I did not see the point adding `BigUint` boilerplate code for one funding.
> Use round decimal number for initial Ether funding

- README.md
Since the release is not working properly yet the readme is reset to
describe downloading the release and running it. Once the release works
properly though `yarn create`/`npx` the readme will change.
Note that the readme is split into creating and running the example, and
the run section is split into environment and application.
I tried to make the previous description more structured but am not totally convinced that it is better (similar complexity...).
> Reset readme to describe setup without release on npm

- README.md
Currently the command to install create-comit-app from source is not
correct, it is missing a period.  Add explicit change directory command
also.
> Fix build from source instructions

- src/start_env/mod.rs
Resolves comit-network/hello-swap#43 because the check interval is every 2 seconds.
If a block was generated every 2 seconds and the check was done every 2 seconds then there was chances for the redeem transaction to be sent but not seen (because not yet mined) by the following check.
Generating faster than checking will ensure that.
> Generate bitcoin blocks every second

- bors.toml
This one isn't running on PRs, so bors always times out.
> Remove license check from required status

- new_project/examples/erc20_btc/README.md
README for this example was missing. Created in similar form as for the separate-apps example.
> erc20-btc example readme

- Cargo.lock
- Cargo.toml
- Makefile
This allows the use of `cargo` on *nix systems without having to pass any additional features.
> Make unix-socket of shiplift a default feature

- .mergify.yml
Even if the CLA does not require signatures for dependabot it still needs to mark the PR as OK which may not happen if the service is down.
Here we ensure that mergify does not tell bors to act until the CLA is marked ok as bors/github will stop the merge otherwise.
> Ensure CLA is sorted before telling bors to merge

- new_project/examples/separate_apps/src/lib.ts
- new_project/examples/separate_apps/src/maker.ts
- new_project/examples/separate_apps/src/taker.ts
This PR fixes the Ethers wallet balance printing after swapping. 
The problem of the initial Bcoin wallet balance is not solved through this, check the updated ticket for more infos: https://github.com/comit-network/create-comit-app/issues/140
> maker sleeps before retrieving Ethereum balance after swap

- Cargo.lock
- Cargo.toml
Does not compile without that on Windows Linux subsystem
> Ensure use-serde is enabled for bitcoin_hashes

- .github/workflows/CI.yml
- .github/workflows/release-bin.yml
- Cargo.lock
- Cargo.toml
- src/docker/mod.rs
The recent release of shiplift (0.6) contains a patch a takes care of the logic that we previously applied ourselves:
https://github.com/softprops/shiplift/pull/193
@luckysori could you please test this one manually on a Windows machine with docker toolbox?
@D4nte / @bonomat  or @da-kami please test if this still works on Mac.
You can download the binaries from the GitHub actions run here (top right): https://github.com/comit-network/create-comit-app/pull/282/checks?check_run_id=341806523
> Remove shiplift host trickery

- Cargo.lock
- Cargo.toml
- src/docker/ethereum.rs
- src/env/mod.rs
- src/env/start.rs
Clarity is a low-level library for Ethereum that implements all the necessary transaction signing for us! <3
Fixes #110.
> Use clarity instead of emerald-rs

- .github/workflows/CI.yml
- Makefile
As GitHub Action does not provide the latest yarn version (1.19.1 instead of 1.21.0), we are getting discrepancies when running `yarn install` which causes CI failure that cannot be (easily) resolved.
Removing this check to remove these failures.
> Remove lockfile check

- .github/workflows/CI.yml
- .github/workflows/release-bin.yml
The latest version of @actions/cache bumped the size limit to 2GB which means we can finally utilize the cache to speed up the builds.
> Cache the target/ folder based on OS, Rust version and dependencies

- .github/workflows/release.yml
- Cargo.lock
- scripts/CHANGELOG.md
- scripts/Cargo.toml
- scripts/npm/.gitignore
- scripts/npm/package.json
~I'll probably have to do the npm releasing for an RC version locally first so I can then assign the new comit-scripts package to comit-network and hopefully this'll give the CI the right to publish further versions.~
I am guessing whoever owns the npm token will be owner of the package and can then move ownership of comit-rs under comit-network.
> Release comit-scripts 0.8.0

- .github/workflows/CI.yml
- Makefile
- create/CHANGELOG.md
- create/new_project/examples/btc_eth/package.json
- create/new_project/examples/btc_eth/src/index.ts
- create/new_project/examples/btc_eth/yarn.lock
- create/new_project/examples/erc20_btc/package.json
- create/new_project/examples/erc20_btc/src/index.ts
- create/new_project/examples/erc20_btc/yarn.lock
- create/new_project/examples/separate_apps/package.json
- create/new_project/examples/separate_apps/src/lib.ts
- create/new_project/examples/separate_apps/src/maker.ts
- create/new_project/examples/separate_apps/src/taker.ts
- create/new_project/examples/separate_apps/yarn.lock
- create/npm/package.json
- create/npm/yarn.lock
- scripts/npm/package.json
- scripts/npm/yarn.lock
- tests/run_example.sh
- Fixes CVE-2019-19919
- upgraded comit-sdk to 0.9.0
- Added TS checks and format check of all JS/TS files.
> Run yarn upgrade in examples

- Cargo.lock
- scripts/CHANGELOG.md
- scripts/Cargo.toml
- scripts/npm/package.json
- `cannot rename` error during start-env has been fixed.
> Release comit-scripts 0.8.2

- create/new_project/demos/btc_eth/package.json
- create/new_project/demos/btc_eth/src/index.ts
- create/new_project/demos/btc_eth/yarn.lock
- create/new_project/demos/erc20_btc/package.json
- create/new_project/demos/erc20_btc/src/index.ts
- create/new_project/demos/erc20_btc/yarn.lock
- create/new_project/examples/btc_eth/package.json
- create/new_project/examples/btc_eth/src/maker.ts
- create/new_project/examples/btc_eth/yarn.lock
- create/new_project/package.json
- scripts/CHANGELOG.md
- scripts/src/docker/cnd.rs
Resolves #119  
Note: our examples did not run, hence, I had to upgrade the comit-sdk to the latest version as well. 
Note: 
Once this is done, we can remove the deprecated API from cnd in https://github.com/comit-network/comit-rs/issues/1580
> Use chain_id for ethereum instead of network string

- create/CHANGELOG.md
- create/new_project/examples/btc_eth/package.json
- create/new_project/examples/btc_eth/src/maker.ts
- create/new_project/examples/btc_eth/src/taker.ts
- create/new_project/examples/btc_eth/yarn.lock
Resolves #371 and comit-network/comit-js-sdk#90.
> Use MakerNegotiator.getUrl(), remove steps for `TakerNegotiator`

- .mergify.yml
We removed it from other repos because it is not helping.
It currently causes problems with mergify due to the `- review-requested!=''` condition.
> Remove changelog nagging

- Cargo.lock
- scripts/Cargo.toml
- scripts/src/docker/bitcoin.rs
- scripts/src/env/start.rs
Use `generatetoaddress` instead of `generate`.
Print wallet descriptor to `env` file instead of extended-priv-key.
This is needed to proceed with the Taker-UI.
> [comit-scripts] Upgrade bitcoind and env file printing

- .github/workflows/release.yml
Changing these paths to be relative was wrong, the `cd` command above is in brackets, meaning it only applies within that context.
> Revert paths to start from project head

- scripts/src/docker/bitcoin.rs
- scripts/src/env/mod.rs
Create a wallet specifically for comit-scripts that is used for initial funding and periodically generating blocks (simulated mining).
Without a wallet the simulated mining (block generation every 1 secs) will fail, because it now uses `getnewaddress` and `generatetoaddress`.
Favored using a specific wallet over the default wallet, because it is more resilient against changes.
> Bitcoin comit-scripts wallet for funding and block generation
